create extension if not exists pgcrypto;
create table if not exists actors (id uuid primary key default gen_random_uuid(), actor_type text not null check (actor_type in ('human','ai')), display_name text not null, auth_user_id uuid unique references auth.users(id), external_key text unique, avatar_url text, created_at timestamptz not null default now());
create table if not exists photos (id uuid primary key default gen_random_uuid(), owner_user_id uuid not null references auth.users(id), storage_path text not null, thumb_path text not null, original_filename text, original_mime text, output_mime text not null default 'image/webp', original_bytes bigint, display_bytes bigint, width integer, height integer, taken_at timestamptz, uploaded_at timestamptz not null default now(), exif jsonb not null default '{}'::jsonb, sha256 text, title text, caption text, favorite boolean not null default false, processing_status text not null default 'ready', deleted_at timestamptz, created_by_actor_id uuid references actors(id), updated_at timestamptz not null default now());
create unique index if not exists photos_sha256_active_idx on photos(owner_user_id,sha256) where deleted_at is null and sha256 is not null;
create table if not exists photo_comments (id uuid primary key default gen_random_uuid(), photo_id uuid not null references photos(id) on delete cascade, author_actor_id uuid not null references actors(id), body text not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), edited_by_actor_id uuid references actors(id), deleted_at timestamptz);
grant select, insert, update, delete on actors, photos, photo_comments to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant select, insert, update, delete on actors, photos, photo_comments to service_role;
grant usage, select on all sequences in schema public to service_role;
insert into storage.buckets (id,name,public) values ('album-private','album-private',false) on conflict (id) do update set public=false;
alter table actors enable row level security; alter table photos enable row level security; alter table photo_comments enable row level security;
create policy "owner actors" on actors for select to authenticated using (auth.uid()=auth_user_id or actor_type='ai');
create policy "owner photos" on photos for all to authenticated using (auth.uid()=owner_user_id) with check (auth.uid()=owner_user_id);
create policy "owner comments read" on photo_comments for select to authenticated using (exists(select 1 from photos p where p.id=photo_id and p.owner_user_id=auth.uid()));
create policy "owner comments write" on photo_comments for insert to authenticated with check (exists(select 1 from photos p where p.id=photo_id and p.owner_user_id=auth.uid()));
create policy "owner comments update" on photo_comments for update to authenticated using (exists(select 1 from photos p where p.id=photo_id and p.owner_user_id=auth.uid())) with check (exists(select 1 from photos p where p.id=photo_id and p.owner_user_id=auth.uid()));
create policy "owner comments delete" on photo_comments for delete to authenticated using (exists(select 1 from photos p where p.id=photo_id and p.owner_user_id=auth.uid()));
create policy "private album read" on storage.objects for select to authenticated using (bucket_id='album-private' and exists(select 1 from photos p where p.owner_user_id=auth.uid() and (p.storage_path=name or p.thumb_path=name)));
create policy "private album insert" on storage.objects for insert to authenticated with check (bucket_id='album-private');
create policy "private album update" on storage.objects for update to authenticated using (bucket_id='album-private') with check (bucket_id='album-private');
create policy "private album delete" on storage.objects for delete to authenticated using (bucket_id='album-private');
