import express from "express";
import { escapeHtml, oauth, ownerPasswordMatches } from "./oauth.js";

const required = (name) => { const value = process.env[name]; if (!value) throw new Error(`Missing ${name}`); return value; };
const supabaseUrl = required("SUPABASE_URL").replace(/\/$/, "");
const serviceKey = required("SUPABASE_SERVICE_ROLE_KEY");
const mcpToken = required("ALBUM_MCP_TOKEN");
const actorKey = process.env.AI_ACTOR_KEY || "evan";
const geminiKey = process.env.GEMINI_API_KEY;
const visionModel = process.env.GEMINI_VISION_MODEL || "gemini-flash-latest";
const embeddingModel = process.env.GEMINI_EMBEDDING_MODEL || "gemini-embedding-001";
const app = express(); app.use(express.json({limit:"1mb"})); app.use(express.urlencoded({extended:false}));
const headers = {apikey:serviceKey, Authorization:`Bearer ${serviceKey}`, "Content-Type":"application/json"};
async function db(path, options={}) { const r=await fetch(`${supabaseUrl}/rest/v1/${path}`,{...options,headers:{...headers,...(options.headers||{})}}); const text=await r.text(); if(!r.ok) throw new Error(`${r.status}: ${text}`); return text?JSON.parse(text):null; }
async function signed(path){const r=await fetch(`${supabaseUrl}/storage/v1/object/sign/album-private/${path}`,{method:"POST",headers,body:JSON.stringify({expiresIn:300})});const j=await r.json();if(!r.ok)throw new Error(JSON.stringify(j));return `${supabaseUrl}/storage/v1${j.signedURL}`;}
async function inlineImage(path){const encodedPath=path.split("/").map(encodeURIComponent).join("/");const r=await fetch(`${supabaseUrl}/storage/v1/object/album-private/${encodedPath}`,{headers:{apikey:serviceKey,Authorization:`Bearer ${serviceKey}`}});if(!r.ok)throw new Error(`Unable to read private thumbnail: ${r.status}`);const bytes=Buffer.from(await r.arrayBuffer());if(bytes.length>750_000)return null;const mimeType=r.headers.get("content-type")||"image/webp";if(!mimeType.startsWith("image/"))throw new Error("Stored thumbnail is not an image");return {type:"image",data:bytes.toString("base64"),mimeType};}
async function readImage(path){const encodedPath=path.split("/").map(encodeURIComponent).join("/");const r=await fetch(`${supabaseUrl}/storage/v1/object/album-private/${encodedPath}`,{headers:{apikey:serviceKey,Authorization:`Bearer ${serviceKey}`}});if(!r.ok)throw new Error(`Unable to read private thumbnail: ${r.status}`);const bytes=Buffer.from(await r.arrayBuffer());if(bytes.length>8_000_000)throw new Error("thumbnail is too large for AI analysis; re-upload or regenerate a smaller thumbnail");const mimeType=r.headers.get("content-type")||"image/webp";if(!mimeType.startsWith("image/"))throw new Error("Stored thumbnail is not an image");return {base64:bytes.toString("base64"),mimeType};}
async function gemini(path,body){if(!geminiKey)throw new Error("AI analysis is not configured yet: set GEMINI_API_KEY on the MCP server");const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/${path}`,{method:"POST",headers:{"x-goog-api-key":geminiKey,"Content-Type":"application/json"},body:JSON.stringify(body)});const text=await r.text();if(!r.ok){let message=`Gemini request failed (${r.status})`;try{message+=`: ${JSON.parse(text).error?.message||"unknown API error"}`;}catch{}console.error(message);throw new Error(message);}return text?JSON.parse(text):null;}
const analysisSchema={type:"object",additionalProperties:false,required:["summary","tags","ocr_text","people_count","scene_type"],properties:{summary:{type:"string"},tags:{type:"array",items:{type:"string"}},ocr_text:{type:"string"},people_count:{type:"integer",minimum:0},scene_type:{type:"string"}}};
function makeSearchText(photo,analysis){return [photo.title,photo.caption,analysis.summary,analysis.scene_type,...analysis.tags,analysis.ocr_text].filter(Boolean).join("\n").replace(/\s+/g," ").trim().slice(0,12000);}
async function embed(text,taskType){const response=await gemini(`models/${embeddingModel}:embedContent`,{model:`models/${embeddingModel}`,content:{parts:[{text}]},taskType,outputDimensionality:1536});const vector=response.embedding?.values;if(!Array.isArray(vector)||vector.length!==1536)throw new Error(`Unexpected embedding size: ${vector?.length||0}`);return vector;}
async function analyzePhoto(photo,force=false){const existing=await db(`photo_ai_analysis?select=*&photo_id=eq.${encodeURIComponent(photo.id)}`);if(existing[0]&&!force)return existing[0];const image=await readImage(photo.thumb_path);const response=await gemini(`models/${visionModel}:generateContent`,{contents:[{parts:[{text:"Analyze this private family-album photo. Describe only visible, non-sensitive facts. Do not identify people, infer identity, age, health, ethnicity, religion, or other sensitive traits. Transcribe legible text exactly into ocr_text; use an empty string when none. Return ONLY valid JSON with these exact fields: summary (string), tags (array of strings), ocr_text (string), people_count (integer), scene_type (string). Return Chinese tags where natural."},{inlineData:{mimeType:image.mimeType,data:image.base64}}]}],generationConfig:{responseMimeType:"application/json"}});const text=response.candidates?.[0]?.content?.parts?.map(part=>part.text||"").join("");let analysis;try{analysis=JSON.parse(text);}catch{throw new Error("AI analysis returned invalid JSON");}const searchText=makeSearchText(photo,analysis);const now=new Date().toISOString();const rows=await db("photo_ai_analysis?on_conflict=photo_id",{method:"POST",headers:{Prefer:"return=representation,resolution=merge-duplicates"},body:JSON.stringify({photo_id:photo.id,model:visionModel,analysis,search_text:searchText,response_id:response.responseId||null,analyzed_at:now,updated_at:now})});const vector=await embed(searchText,"RETRIEVAL_DOCUMENT");await db("photo_embeddings?on_conflict=photo_id",{method:"POST",headers:{Prefer:"return=minimal,resolution=merge-duplicates"},body:JSON.stringify({photo_id:photo.id,model:embeddingModel,content:searchText,embedding:vector,updated_at:now})});await audit("analyze_photo","photo",photo.id,{model:visionModel});return rows[0]||{photo_id:photo.id,model:visionModel,analysis,search_text:searchText};}
const publicBaseUrl = process.env.PUBLIC_BASE_URL || "https://album-mcp.tehouse.net";
const mcpResource = `${publicBaseUrl}/mcp`;
const tools=[
  {name:"list_photos",description:"列出私人相册中的照片。默认不含已删除照片。",inputSchema:{type:"object",properties:{limit:{type:"integer",minimum:1,maximum:50},favorite:{type:"boolean"}},additionalProperties:false}},
  {name:"get_photo",description:"取得一张照片的 metadata、评论和真实缩略图。支持图片内容的 MCP host 会直接把缩略图交给模型；signed URL 仅作辅助。",inputSchema:{type:"object",properties:{photo_id:{type:"string"}},required:["photo_id"]}},
  {name:"random_photos",description:"随机翻看旧照片。",inputSchema:{type:"object",properties:{count:{type:"integer",minimum:1,maximum:10},favorite:{type:"boolean"}},additionalProperties:false}},
  {name:"update_photo",description:"更新照片的标题、备注、拍摄时间或收藏状态。",inputSchema:{type:"object",properties:{photo_id:{type:"string"},title:{type:"string",maxLength:200},caption:{type:"string",maxLength:4000},taken_at:{type:"string"},favorite:{type:"boolean"}},required:["photo_id"]}},
  {name:"delete_photo",description:"将照片移入回收站（可恢复，不删除 Storage 文件）。",inputSchema:{type:"object",properties:{photo_id:{type:"string"}},required:["photo_id"]}},
  {name:"restore_photo",description:"从回收站恢复一张照片。",inputSchema:{type:"object",properties:{photo_id:{type:"string"}},required:["photo_id"]}},
  {name:"add_comment",description:"以 AI 住户身份在照片下留言。",inputSchema:{type:"object",properties:{photo_id:{type:"string"},body:{type:"string",minLength:1,maxLength:4000}},required:["photo_id","body"]}},
  {name:"edit_comment",description:"编辑 Evan 自己的留言。",inputSchema:{type:"object",properties:{comment_id:{type:"string"},body:{type:"string",minLength:1,maxLength:4000}},required:["comment_id","body"]}},
  {name:"delete_comment",description:"软删除 Evan 自己的一条留言。",inputSchema:{type:"object",properties:{comment_id:{type:"string"}},required:["comment_id"]}},
  {name:"list_albums",description:"列出未删除的相册。",inputSchema:{type:"object",properties:{},additionalProperties:false}},
  {name:"get_album",description:"读取相册详情与其照片。",inputSchema:{type:"object",properties:{album_id:{type:"string"}},required:["album_id"]}},
  {name:"create_album",description:"创建一个新相册。",inputSchema:{type:"object",properties:{title:{type:"string",minLength:1,maxLength:200},description:{type:"string",maxLength:4000}},required:["title"]}},
  {name:"update_album",description:"更新相册名称、说明或封面。",inputSchema:{type:"object",properties:{album_id:{type:"string"},title:{type:"string",minLength:1,maxLength:200},description:{type:"string",maxLength:4000},cover_photo_id:{type:"string"}},required:["album_id"]}},
  {name:"add_photo_to_album",description:"将一张照片加入相册。",inputSchema:{type:"object",properties:{album_id:{type:"string"},photo_id:{type:"string"},position:{type:"integer"}},required:["album_id","photo_id"]}},
  {name:"remove_photo_from_album",description:"从一个相册移除照片，不删除照片本身。",inputSchema:{type:"object",properties:{album_id:{type:"string"},photo_id:{type:"string"}},required:["album_id","photo_id"]}},
  {name:"delete_album",description:"将相册移入回收状态；不删除其中的照片。",inputSchema:{type:"object",properties:{album_id:{type:"string"}},required:["album_id"]}}
  ,{name:"analyze_photo",description:"用 AI 读取一张私有照片，生成中文描述、标签与 OCR，并建立语义搜索索引。不会识别人脸或推断敏感身份。",inputSchema:{type:"object",properties:{photo_id:{type:"string"},force_refresh:{type:"boolean"}},required:["photo_id"],additionalProperties:false}}
  ,{name:"search_photos",description:"按自然语言语义搜索已完成 AI 分析的照片，例如“有猫的沙发”或“写着菜单的照片”。",inputSchema:{type:"object",properties:{query:{type:"string",minLength:1,maxLength:1000},limit:{type:"integer",minimum:1,maximum:30},min_similarity:{type:"number",minimum:0,maximum:1}},required:["query"],additionalProperties:false}}
];
let cachedAiActor;
async function aiActor(){if(cachedAiActor)return cachedAiActor;const rows=await db(`actors?select=id&external_key=eq.${encodeURIComponent(actorKey)}&actor_type=eq.ai`);if(!rows[0])throw new Error(`AI actor not found: ${actorKey}`);cachedAiActor=rows[0];return cachedAiActor;}
async function ownerUserId(){const rows=await db("actors?select=auth_user_id&actor_type=eq.human&auth_user_id=not.is.null&limit=1");if(!rows[0]?.auth_user_id)throw new Error("Human owner actor not found");return rows[0].auth_user_id;}
async function audit(action,entityType,entityId,payload={}){const actor=await aiActor();await db("audit_log",{method:"POST",headers:{Prefer:"return=minimal"},body:JSON.stringify({actor_id:actor.id,action,entity_type:entityType,entity_id:String(entityId),payload})});}
function compact(value){return Object.fromEntries(Object.entries(value).filter(([,v])=>v!==undefined));}
async function callTool(name,args){
  if(name==="list_photos"){const favorite=args.favorite===undefined?"":`&favorite=eq.${args.favorite}`;const rows=await db(`photos?select=id,title,caption,taken_at,thumb_path,storage_path,favorite&deleted_at=is.null${favorite}&order=taken_at.desc.nullslast&limit=${Math.min(args.limit||20,50)}`);return Promise.all(rows.map(async p=>({...p,thumb_url:await signed(p.thumb_path)})));}
  if(name==="get_photo"){const rows=await db(`photos?select=*&id=eq.${encodeURIComponent(args.photo_id)}&deleted_at=is.null`);if(!rows[0])throw new Error("photo not found");const p=rows[0];const [comments,imageUrl,image]=await Promise.all([db(`photo_comments?select=id,body,created_at,author_actor:actors!photo_comments_author_actor_id_fkey(display_name)&photo_id=eq.${p.id}&deleted_at=is.null&order=created_at.asc`),signed(p.storage_path),inlineImage(p.thumb_path)]);return {...p,image_url:imageUrl,comments,_inline_image:image};}
  if(name==="analyze_photo"){const rows=await db(`photos?select=id,title,caption,thumb_path&deleted_at=is.null&id=eq.${encodeURIComponent(args.photo_id)}`);if(!rows[0])throw new Error("photo not found");return analyzePhoto(rows[0],args.force_refresh===true);}
  if(name==="search_photos"){const vector=await embed(args.query,"RETRIEVAL_QUERY");const matches=await db("rpc/match_album_photo_embeddings",{method:"POST",body:JSON.stringify({query_embedding:vector,match_count:Math.min(args.limit||10,30),min_similarity:args.min_similarity??0.20})});if(!matches.length)return {query:args.query,photos:[],note:"No analyzed photos matched yet. Run analyze_photo on photos first."};const ids=matches.map(x=>x.photo_id);const photos=await db(`photos?select=id,title,caption,taken_at,thumb_path,favorite&id=in.(${ids.join(",")})&deleted_at=is.null`);const byId=new Map(photos.map(p=>[p.id,p]));return {query:args.query,photos:await Promise.all(matches.filter(m=>byId.has(m.photo_id)).map(async m=>({...byId.get(m.photo_id),similarity:m.similarity,match_text:m.content,thumb_url:await signed(byId.get(m.photo_id).thumb_path)})))};}
  if(name==="random_photos"){const favorite=args.favorite===undefined?"":`&favorite=eq.${args.favorite}`;const rows=await db(`photos?select=id,title,caption,taken_at,thumb_path,favorite&deleted_at=is.null${favorite}&limit=500`);return Promise.all(rows.sort(()=>Math.random()-.5).slice(0,Math.min(args.count||3,10)).map(async p=>({...p,thumb_url:await signed(p.thumb_path)})));}
  if(name==="update_photo"){const changes=compact({title:args.title,caption:args.caption,taken_at:args.taken_at,favorite:args.favorite,updated_at:new Date().toISOString()});if(Object.keys(changes).length===1)throw new Error("Provide at least one photo field to update");const rows=await db(`photos?id=eq.${encodeURIComponent(args.photo_id)}&deleted_at=is.null`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(changes)});if(!rows[0])throw new Error("photo not found");await audit("update_photo","photo",args.photo_id,changes);return rows[0];}
  if(name==="delete_photo"||name==="restore_photo"){const deleted=name==="delete_photo";const rows=await db(`photos?id=eq.${encodeURIComponent(args.photo_id)}${deleted?"&deleted_at=is.null":"&deleted_at=not.is.null"}`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({deleted_at:deleted?new Date().toISOString():null,updated_at:new Date().toISOString()})});if(!rows[0])throw new Error(deleted?"photo not found or already deleted":"photo not found in trash");await audit(deleted?"delete_photo":"restore_photo","photo",args.photo_id);return rows[0];}
  if(name==="add_comment"){const actor=await aiActor();const rows=await db("photo_comments",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({photo_id:args.photo_id,author_actor_id:actor.id,body:args.body})});await audit("add_comment","photo_comment",rows[0].id,{photo_id:args.photo_id});return rows[0];}
  if(name==="edit_comment"||name==="delete_comment"){const actor=await aiActor();const deleted=name==="delete_comment";const patch=deleted?{deleted_at:new Date().toISOString(),edited_by_actor_id:actor.id}:{body:args.body,updated_at:new Date().toISOString(),edited_by_actor_id:actor.id};const rows=await db(`photo_comments?id=eq.${encodeURIComponent(args.comment_id)}&author_actor_id=eq.${actor.id}&deleted_at=is.null`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(patch)});if(!rows[0])throw new Error("comment not found or not authored by this AI");await audit(deleted?"delete_comment":"edit_comment","photo_comment",args.comment_id);return rows[0];}
  if(name==="list_albums"){return db("albums?select=id,title,description,cover_photo_id,created_at,updated_at&deleted_at=is.null&order=updated_at.desc");}
  if(name==="get_album"){const albums=await db(`albums?select=*&id=eq.${encodeURIComponent(args.album_id)}&deleted_at=is.null`);if(!albums[0])throw new Error("album not found");const photos=await db(`album_photos?select=position,added_at,photo:photos(id,title,caption,taken_at,thumb_path,favorite)&album_id=eq.${encodeURIComponent(args.album_id)}&order=position.asc.nullslast,added_at.asc`);return {...albums[0],photos:await Promise.all(photos.map(async x=>({...x,photo:x.photo?{...x.photo,thumb_url:await signed(x.photo.thumb_path)}:null})))};}
  if(name==="create_album"){const actor=await aiActor();const rows=await db("albums",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify({owner_user_id:await ownerUserId(),title:args.title,description:args.description||null,created_by_actor_id:actor.id})});await audit("create_album","album",rows[0].id);return rows[0];}
  if(name==="update_album"){const changes=compact({title:args.title,description:args.description,cover_photo_id:args.cover_photo_id,updated_at:new Date().toISOString()});if(Object.keys(changes).length===1)throw new Error("Provide at least one album field to update");const rows=await db(`albums?id=eq.${encodeURIComponent(args.album_id)}&deleted_at=is.null`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify(changes)});if(!rows[0])throw new Error("album not found");await audit("update_album","album",args.album_id,changes);return rows[0];}
  if(name==="add_photo_to_album"){const actor=await aiActor();const rows=await db("album_photos",{method:"POST",headers:{Prefer:"return=representation,resolution=merge-duplicates"},body:JSON.stringify({album_id:args.album_id,photo_id:args.photo_id,position:args.position??null,added_by_actor_id:actor.id})});await audit("add_photo_to_album","album",args.album_id,{photo_id:args.photo_id});return rows[0];}
  if(name==="remove_photo_from_album"){const rows=await db(`album_photos?album_id=eq.${encodeURIComponent(args.album_id)}&photo_id=eq.${encodeURIComponent(args.photo_id)}`,{method:"DELETE",headers:{Prefer:"return=representation"}});if(!rows[0])throw new Error("photo is not in this album");await audit("remove_photo_from_album","album",args.album_id,{photo_id:args.photo_id});return rows[0];}
  if(name==="delete_album"){const rows=await db(`albums?id=eq.${encodeURIComponent(args.album_id)}&deleted_at=is.null`,{method:"PATCH",headers:{Prefer:"return=representation"},body:JSON.stringify({deleted_at:new Date().toISOString(),updated_at:new Date().toISOString()})});if(!rows[0])throw new Error("album not found or already deleted");await audit("delete_album","album",args.album_id);return rows[0];}
  throw new Error(`Unknown tool: ${name}`);
}
function authorized(req){return req.get("authorization")===`Bearer ${mcpToken}`;}
function oauthAuthorized(req){const value=req.get("authorization")?.match(/^Bearer\s+(.+)$/i)?.[1];return Boolean(value&&oauth.validAccess(value,mcpResource));}
app.get("/health",(_,res)=>res.json({ok:true,service:"te-album-mcp",version:"0.1.0"}));
app.get("/.well-known/oauth-protected-resource",(_,res)=>res.json(oauth.resourceMetadata(publicBaseUrl,mcpResource)));
app.get("/.well-known/oauth-protected-resource/mcp",(_,res)=>res.json(oauth.resourceMetadata(publicBaseUrl,mcpResource)));
app.get("/.well-known/oauth-authorization-server",(_,res)=>res.json(oauth.metadata(publicBaseUrl,mcpResource)));
app.post("/oauth/register",(req,res)=>{try{res.status(201).json(oauth.register(req.body||{}));}catch(e){res.status(400).json({error:"invalid_client_metadata",error_description:e.message});}});
app.get("/oauth/authorize",(req,res)=>{try{const request=oauth.validate(req.query,mcpResource);const fields=Object.entries(req.query).map(([k,v])=>`<input type="hidden" name="${escapeHtml(k)}" value="${escapeHtml(v)}">`).join("");res.type("html").send(`<!doctype html><meta charset="utf-8"><title>连接 TE 相册</title><style>body{font:16px system-ui;max-width:420px;margin:12vh auto;padding:24px;background:#f5f1eb;color:#272521}main{background:white;padding:28px;border-radius:18px}input{width:100%;box-sizing:border-box;padding:12px;margin:8px 0 16px}button{width:100%;padding:12px;background:#272521;color:white;border:0;border-radius:8px}</style><main><h1>连接 TE 相册</h1><p>允许 Claude 读取照片并以 AI 住户身份留言。</p><form method="post" action="/oauth/authorize">${fields}<label>相册授权密码</label><input name="password" type="password" required autofocus><button>允许并连接</button></form></main>`);}catch(e){res.status(400).send(e.message);}});
app.post("/oauth/authorize",(req,res)=>{try{const request=oauth.validate(req.body,mcpResource);if(!ownerPasswordMatches(req.body.password))return res.status(403).send("授权密码不正确");const code=oauth.issueCode(request);const callback=new URL(request.redirectUri);callback.searchParams.set("code",code);if(request.state)callback.searchParams.set("state",request.state);res.redirect(callback.toString());}catch(e){res.status(400).send(e.message);}});
app.post("/oauth/token",(req,res)=>{try{const result=req.body.grant_type==="refresh_token"?oauth.refresh(req.body):oauth.exchange(req.body);res.set("Cache-Control","no-store").json(result);}catch(e){res.status(400).json({error:"invalid_grant",error_description:e.message});}});
app.post("/mcp",async(req,res)=>{if(!authorized(req)&&!oauthAuthorized(req)){res.set("WWW-Authenticate",`Bearer resource_metadata="${publicBaseUrl}/.well-known/oauth-protected-resource/mcp"`).status(401).json({error:"unauthorized"});return;}const {id,method,params={}}=req.body||{};try{let result;if(method==="initialize")result={protocolVersion:"2025-03-26",capabilities:{tools:{}},serverInfo:{name:"te-album-mcp",version:"0.1.0"}};else if(method==="notifications/initialized")return res.status(202).end();else if(method==="tools/list")result={tools};else if(method==="tools/call"){const value=await callTool(params.name,params.arguments||{});const image=value?._inline_image; if(image)delete value._inline_image;result={content:[{type:"text",text:JSON.stringify(value)},...(image?[image]:[])]};}else result={};res.json({jsonrpc:"2.0",id,result});}catch(error){console.error("MCP tool failed",params?.name,error);res.status(200).json({jsonrpc:"2.0",id,error:{code:-32000,message:error.message}});}});
const port=Number(process.env.PORT||3001);app.listen(port,()=>console.log(`TE album MCP listening on ${port}`));
